name: first_project
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1



environment:
  sdk: '>=3.1.2 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:

    sdk: flutter
  flutter_spinkit: ^5.2.0
  flutter_native_splash: ^2.3.2
  google_fonts: ^6.1.0
  sidebarx: ^0.16.2
  curved_navigation_bar: ^1.0.3 #latest version
  flutter_svg: ^2.0.7
  awesome_dialog: ^3.1.0
  firebase_core: ^2.20.0
  cloud_firestore: ^4.12.0
  firebase_auth: ^4.6.3
  firebase_storage: ^11.2.4
  fluttertoast: ^8.2.2
  shared_preferences: ^2.0.7
  draggable_fab: ^0.1.4
  animated_text_kit: ^4.2.1     #for_animated_typing_in_ai
  dash_chat_2: ^0.0.15
  chat_gpt_sdk: ^2.2.5
  image_picker: ^0.8.4+4
  cached_network_image: ^3.0.0
  flutter_cache_manager: ^3.3.1
  permission_handler: ^10.0.0
  charts_flutter: ^0.12.0
  intl: ^0.17.0
  flare_flutter: ^3.0.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0




# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  assets:
    - assets/logo.gif
    - assets/logo2.gif
    - assets/codex.png
    - assets/codexname.png
    - assets/finalogo.png
    - assets/finalogo2.png
    - assets/E.png
    - assets/jrizal.jpg
    - assets/EafbSjcXgAEv71t_edge.png
    - assets/1.gif
    - assets/2.gif
    - assets/3.gif
    - assets/4.gif
    - assets/5.gif
    - assets/ai/chatbot_response.json
    - assets/ai/ai_responses/java/java_syntax.jpg
    - assets/final_game.png
    - assets/final_machine.png
    - assets/final_mobile.png
    - assets/final_web.png
    - assets/triangles.png
    - assets/whitemosaic.jpg
    - assets/colorfulmosaic.jpg
    - assets/blueshade.jpg
    - assets/white_and_lightblue.jpg
    - assets/logorizal_4.png
    - assets/fireworks.gif
    - assets/confetti.gif

      #C
    - assets/C/ss1.png
    - assets/C/ss2.png
    - assets/C/ss3.png
    - assets/C/ss4.png
    - assets/C/ss6.png
    - assets/C/ss7.png
    - assets/C/ss8.png
    - assets/C/ss9.png
    - assets/C/ss10.png
    - assets/C/ss11.png
    - assets/C/ss12.png
    - assets/C/ss13.png
    - assets/C/ss14.png
    - assets/C/ss15.png
    - assets/C/ss16.png
    - assets/C/ss17.png
    - assets/C/ss18.png
    - assets/C/ss19.png
    - assets/C/ss20.png
    - assets/C/ss21.png
    - assets/C/ss22.png
    - assets/C/ss23.png
    - assets/C/ss24.png
    - assets/C/ss25.png
    - assets/C/ss26.png
    - assets/C/ss27.png
    - assets/C/s28.png
    - assets/C/s29.png
    - assets/C/s30.png
    - assets/C/s31.png
    - assets/C/s32.png
    - assets/C/s33.png
    - assets/C/s34.png
    - assets/C/s35.png
    - assets/C/s36.png
    - assets/C/s37.png
    - assets/C/s38.png
    - assets/C/s39.png
    - assets/C/s40.png
    - assets/C/s41.png
    - assets/C/s42.png
    - assets/C/s43.png
    - assets/C/s44.png
    - assets/C/s45.png
    - assets/C/s46.png
    - assets/C/s47.png
    - assets/C/s48.png
    - assets/C/s49.png
    - assets/C/s50.png
    - assets/C/s51.png
    - assets/C/s52.png
    - assets/C/s53.png
    - assets/C/s54.png
    - assets/C/s55.png
    - assets/C/s56.png
    - assets/C/s56.png
    - assets/C/s57.png
    - assets/C/s58.png
    - assets/C/s59.png
    - assets/C/s60.png
    - assets/C/s61.png
    - assets/C/s62.png
    - assets/C/s63.png
    - assets/C/s64.png
    - assets/C/s65.png








    - assets/stamp/stamp.png
    - assets/java_lessons_image/get_started1.png
    - assets/java_lessons_image/get_started2.jpg
    - assets/java_lessons_image/step1_get_started.jpg
    - assets/java_lessons_image/step2_get_started.jpg
    - assets/java_lessons_image/step3_get_started.jpg
    - assets/java_lessons_image/step4_get_started.jpg
    - assets/java_lessons_image/step5_get_started.jpg
    - assets/java_lessons_image/step6_get_started.jpg
    - assets/java_lessons_image/step7_get_started.jpg
    - assets/java_lessons_image/step8_get_started.jpg
    - assets/java_lessons_image/step9_get_started.jpg
    - assets/java_lessons_image/step10_get_started.jpg
    - assets/java_lessons_image/syntax_1.jpg
    - assets/java_lessons_image/syntax_2.jpg
    - assets/java_lessons_image/output_text_1.jpg
    - assets/java_lessons_image/output_text_2.jpg
    - assets/java_lessons_image/output_text_3.jpg
    - assets/java_lessons_image/output_text_4.jpg
    - assets/java_lessons_image/output_number_1.jpg
    - assets/java_lessons_image/output_number_2.jpg
    - assets/java_lessons_image/output_number_3.jpg
    - assets/java_lessons_image/comments_1.jpg
    - assets/java_lessons_image/comments_2.jpg
    - assets/java_lessons_image/comments_3.jpg
    - assets/java_lessons_image/variables_1.jpg
    - assets/java_lessons_image/variables_2.jpg
    - assets/java_lessons_image/variables_3.jpg
    - assets/java_lessons_image/variables_4.jpg
    - assets/java_lessons_image/variables_5.jpg
    - assets/java_lessons_image/variables_6.jpg
    - assets/java_lessons_image/variables_7.jpg
    - assets/java_lessons_image/variables_8.jpg
    - assets/java_lessons_image/variables_9.jpg
    - assets/java_lessons_image/variables_10.jpg
    - assets/java_lessons_image/variables_11.jpg
    - assets/java_lessons_image/variables_12.jpg
    - assets/java_lessons_image/variables_13.jpg
    - assets/java_lessons_image/variables_14.jpg
    - assets/java_lessons_image/dtypes_1.jpg
    - assets/java_lessons_image/dtypes_2.jpg
    - assets/java_lessons_image/number_1.jpg
    - assets/java_lessons_image/number_2.jpg
    - assets/java_lessons_image/number_3.jpg
    - assets/java_lessons_image/number_4.jpg
    - assets/java_lessons_image/number_5.jpg
    - assets/java_lessons_image/number_6.jpg
    - assets/java_lessons_image/number_7.jpg
    - assets/java_lessons_image/boo_1.jpg
    - assets/java_lessons_image/char_1.jpg
    - assets/java_lessons_image/char_2.jpg
    - assets/java_lessons_image/char_3.jpg
    - assets/java_lessons_image/cast_1.jpg
    - assets/java_lessons_image/op_1.jpg
    - assets/java_lessons_image/op_2.jpg
    - assets/java_lessons_image/op_3.jpg
    - assets/java_lessons_image/op_4.jpg
    - assets/java_lessons_image/op_5.jpg
    - assets/java_lessons_image/op_6.jpg
    - assets/java_lessons_image/op_7.jpg
    - assets/java_lessons_image/op_8.jpg
    - assets/java_lessons_image/op_9.jpg
    - assets/java_lessons_image/string_1.jpg
    - assets/java_lessons_image/string_2.jpg
    - assets/java_lessons_image/string_3.jpg
    - assets/java_lessons_image/string_4.jpg
    - assets/java_lessons_image/scon_1.jpg
    - assets/java_lessons_image/scon_2.jpg
    - assets/java_lessons_image/numstring_1.jpg
    - assets/java_lessons_image/numstring_2.jpg
    - assets/java_lessons_image/numstring_3.jpg
    - assets/java_lessons_image/javamath_1.jpg
    - assets/java_lessons_image/javamath_2.jpg
    - assets/java_lessons_image/javamath_3.jpg
    - assets/java_lessons_image/javamath_4.jpg
    - assets/java_lessons_image/javamath_5.jpg
    - assets/java_lessons_image/javamath_6.jpg
    - assets/java_lessons_image/bool_1.jpg
    - assets/java_lessons_image/bool_2.jpg
    - assets/java_lessons_image/bool_3.jpg
    - assets/java_lessons_image/bool_4.jpg
    - assets/java_lessons_image/bool_5.jpg
    - assets/java_lessons_image/bool_6.jpg
    - assets/java_lessons_image/bool_7.jpg
    - assets/java_lessons_image/javaelse_1.jpg
    - assets/java_lessons_image/javaelse_2.jpg
    - assets/java_lessons_image/javaelse_3.jpg
    - assets/java_lessons_image/javaelse_4.jpg
    - assets/java_lessons_image/javaelse_5.jpg
    - assets/java_lessons_image/javaelse_6.jpg
    - assets/java_lessons_image/javaelse_7.jpg
    - assets/java_lessons_image/shorthand_1.jpg
    - assets/java_lessons_image/shorthand_2.jpg
    - assets/java_lessons_image/shorthand_3.jpg
    - assets/java_lessons_image/switch_1.jpg
    - assets/java_lessons_image/switch_2.jpg
    - assets/java_lessons_image/switch_3.jpg
    - assets/java_lessons_image/while_1.jpg
    - assets/java_lessons_image/while_2.jpg
    - assets/java_lessons_image/while_3.jpg
    - assets/java_lessons_image/while_4.jpg
    - assets/java_lessons_image/for_1.jpg
    - assets/java_lessons_image/for_2.jpg
    - assets/java_lessons_image/for_3.jpg
    - assets/java_lessons_image/for_4.jpg
    - assets/java_lessons_image/each_1.jpg
    - assets/java_lessons_image/each_2.jpg
    - assets/java_lessons_image/break_1.jpg
    - assets/java_lessons_image/break_2.jpg
    - assets/java_lessons_image/break_3.jpg
    - assets/java_lessons_image/break_4.jpg
    - assets/java_lessons_image/array_1.jpg
    - assets/java_lessons_image/array_2.jpg
    - assets/java_lessons_image/array_3.jpg
    - assets/java_lessons_image/array_4.jpg
    - assets/java_lessons_image/array_5.jpg
    - assets/java_lessons_image/array_6.jpg
    - assets/java_lessons_image/array_7.jpg
    - assets/java_lessons_image/allop_1.jpg
    - assets/java_lessons_image/allop_2.jpg
    - assets/java_lessons_image/allop_3.jpg
    - assets/java_lessons_image/multi_1.jpg
    - assets/java_lessons_image/multi_2.jpg
    - assets/java_lessons_image/multi_3.jpg
    - assets/java_lessons_image/multi_4.jpg

    #Java Interm
    - assets/java_intermediate/oop_1.png
    - assets/java_intermediate/oop_2.png
    #Java Classes and Objects
    - assets/java_intermediate/cla_1.png
    - assets/java_intermediate/cla_2.png
    - assets/java_intermediate/cla_3.png
    - assets/java_intermediate/cla_4.png
    - assets/java_intermediate/cla_5.png
    - assets/java_intermediate/cla_6.png
    - assets/java_intermediate/cla_7.png
    - assets/java_intermediate/cla_8.png
     #JAVA ATTRIBUTES
    - assets/java_intermediate/att_1.png
    - assets/java_intermediate/att_2.png
    - assets/java_intermediate/att_3.png
    - assets/java_intermediate/att_4.png
    - assets/java_intermediate/att_5.png
    - assets/java_intermediate/att_6.png
    - assets/java_intermediate/att_7.png
    # Java Class Methods
    - assets/java_intermediate/cmet_1.png
    - assets/java_intermediate/cmet_2.png
    - assets/java_intermediate/cmet_3.png
    - assets/java_intermediate/cmet_4.png
    - assets/java_intermediate/cmet_5.png
    - assets/java_intermediate/cmet_6.png
    - assets/java_intermediate/cmet_7.png
    - assets/java_intermediate/cmet_8.png
    - assets/java_intermediate/cmet_9.png
    #Java Constructors
    - assets/java_intermediate/cons_1.png
    - assets/java_intermediate/cons_2.png
    - assets/java_intermediate/cons_3.png
    # Java Methods
    - assets/java_intermediate/met_1.png
    - assets/java_intermediate/met_2.png
    - assets/java_intermediate/met_3.png
    #Java Method Parameters
    - assets/java_intermediate/mpar_1.png
    - assets/java_intermediate/mpar_2.png
    - assets/java_intermediate/mpar_2.png
    - assets/java_intermediate/mpar_3.png
    - assets/java_intermediate/mpar_4.png
    - assets/java_intermediate/mpar_5.png
    - assets/java_intermediate/mpar_6.png
    #Java Method Overloading
    - assets/java_intermediate/over_1.png
    - assets/java_intermediate/over_2.png
    - assets/java_intermediate/over_3.png
    #Java Scope
    - assets/java_intermediate/scope_1.png
    - assets/java_intermediate/scope_2.png
    #Java Recursion
    - assets/java_intermediate/rec_1.png
    - assets/java_intermediate/rec_2.png
    - assets/java_intermediate/rec_3.png
    #Java Modifiers
    - assets/java_advance/mod_1.png
    - assets/java_advance/mod_2.png
    - assets/java_advance/mod_3.png
    - assets/java_advance/mod_4.png
    - assets/java_advance/mod_5.png
    - assets/java_advance/mod_6.png
    - assets/java_advance/mod_7.png
    - assets/java_advance/mod_8.png
    # Java Encapsulation
    - assets/java_advance/encap_1.png
    - assets/java_advance/encap_2.png
    - assets/java_advance/encap_3.png
    - assets/java_advance/encap_4.png
    #Java Packages
    - assets/java_advance/pack_1.png
    - assets/java_advance/pack_2.png
    - assets/java_advance/pack_3.png
    - assets/java_advance/pack_4.png
    - assets/java_advance/pack_5.png
    - assets/java_advance/pack_6.png
    - assets/java_advance/pack_7.png
    - assets/java_advance/pack_8.png
    - assets/java_advance/pack_9.png
    - assets/java_advance/pack_10.png
    #Java Inheritance
    - assets/java_advance/inhe_1.png
    #Java Polymorphism
    - assets/java_advance/poly_1.png
    - assets/java_advance/poly_2.png
    #Java Inner Classes
    - assets/java_advance/inn_1.png
    - assets/java_advance/inn_2.png
    - assets/java_advance/inn_3.png
    - assets/java_advance/inn_4.png
    - assets/java_advance/inn_5.png
    #Java Abstraction
    - assets/java_advance/abs_1.png
    - assets/java_advance/abs_2.png
    #Java Interface
    - assets/java_advance/inter_1.png
    - assets/java_advance/inter_2.png
    - assets/java_advance/inter_3.png
    #Java Enums
    - assets/java_advance/enums_1.png
    - assets/java_advance/enums_2.png
    - assets/java_advance/enums_3.png
    - assets/java_advance/enums_4.png
    - assets/java_advance/enums_5.png
    - assets/java_advance/enums_6.png
    - assets/java_advance/enums_7.png
    - assets/java_advance/enums_8.png
    #Java User Input (Scanner)
    - assets/java_advance/user_1.png
    - assets/java_advance/user_2.png
    - assets/java_advance/user_3.png
    #Java Date and Time
    - assets/java_advance/date_1.png
    - assets/java_advance/date_2.png
    - assets/java_advance/date_3.png
    - assets/java_advance/date_4.png
    - assets/java_advance/date_5.png
    - assets/java_advance/date_6.png
    - assets/java_advance/date_7.png
    - assets/java_advance/date_8.png
    - assets/java_advance/date_9.png
    #Java ArrayList
    - assets/java_advance/array_1.png
    - assets/java_advance/array_2.png
    - assets/java_advance/array_3.png
    - assets/java_advance/array_4.png
    - assets/java_advance/array_5.png
    - assets/java_advance/array_6.png
    - assets/java_advance/array_7.png
    - assets/java_advance/array_8.png
    - assets/java_advance/array_9.png
    - assets/java_advance/array_10.png
    - assets/java_advance/array_11.png
    - assets/java_advance/array_12.png
    #Java LinkedList
    - assets/java_advance/linked_1.png
    - assets/java_advance/linked_2.png
    #Java HashMap
    - assets/java_advance/hash_1.png
    - assets/java_advance/hash_2.png
    - assets/java_advance/hash_3.png
    - assets/java_advance/hash_4.png
    - assets/java_advance/hash_5.png
    - assets/java_advance/hash_6.png
    - assets/java_advance/hash_7.png
    - assets/java_advance/hash_8.png
    - assets/java_advance/hash_9.png
    - assets/java_advance/hash_10.png
    #Java HashSet
    - assets/java_advance/set_1.png
    - assets/java_advance/set_2.png
    - assets/java_advance/set_3.png
    - assets/java_advance/set_4.png
    - assets/java_advance/set_5.png
    - assets/java_advance/set_6.png
    - assets/java_advance/set_7.png
    - assets/java_advance/set_8.png
    #Java Iterator
    - assets/java_advance/ite_1.png
    - assets/java_advance/ite_2.png
    - assets/java_advance/ite_3.png
    #Java Wrapper Classes
    - assets/java_advance/wrap_1.png
    - assets/java_advance/wrap_2.png
    - assets/java_advance/wrap_3.png
    - assets/java_advance/wrap_4.png
    - assets/java_advance/wrap_5.png
    #Java Exceptions
    - assets/java_advance/ex_1.png
    - assets/java_advance/ex_2.png
    - assets/java_advance/ex_3.png
    - assets/java_advance/ex_4.png
    - assets/java_advance/ex_5.png
    - assets/java_advance/ex_6.png
    - assets/java_advance/ex_7.png
    - assets/java_advance/ex_8.png
    - assets/java_advance/ex_9.png
    - assets/java_advance/ex_10.png
    - assets/java_advance/ex_11.png
    #Java Regular Expressions
    - assets/java_advance/reg_1.png
    - assets/java_advance/reg_2.png
    - assets/java_advance/reg_3.png
    - assets/java_advance/reg_4.png
    #Java Threads
    - assets/java_advance/thread_1.png
    - assets/java_advance/thread_2.png
    - assets/java_advance/thread_3.png
    - assets/java_advance/thread_4.png
    - assets/java_advance/thread_5.png
    - assets/java_advance/thread_6.png
    #Java Lambda Expressions
    - assets/java_advance/lamb_1.png
    - assets/java_advance/lamb_2.png
    - assets/java_advance/lamb_3.png
    - assets/java_advance/lamb_4.png
    - assets/java_advance/lamb_5.png
    - assets/java_advance/lamb_6.png























  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
